### ISSUE TITLE
测试无法爬取了

### ISSUE THREAD

**Issue by WhiteFoxLYJ** [songguoxiong/wenshu_utils#2]
最近测试模拟获取vjkl5后获取listContent 和 用了您的代码也测试了一变，请求状态码 200，但是都无法成功获取，看了request构造和之前没有改变，这是什么原因呢？请大牛执教，谢谢！

**Comment by songguoxiong** [comment]
更新了代码，再试试demo.py。

另外发现好像有ip问题，就是某一流程下来ip需要同一个。(**不太确定，没仔细测试**)
比如文书详情页的流程：
1. 第一次请求接口返回"请开启JavaScript并刷新该页"，此时请求为ip A。
2. 解析第一次请求返回的js得到一个url，如果这时继续使用ip A请求则能返回数据，如果使用了新的ip B则继续返回"请开启JavaScript并刷新该页"。ip B想要获取到数据只能用再次解析js得到url用ip B再次请求一次

暂时推测是wzws_cid这个cookie和ip有绑定关系如果wzws_cid和ip对不上，则会返回"请开启JavaScript并刷新该页"

**Comment by WhiteFoxLYJ** [comment]
明白了，感谢大牛指教，十分感谢。
