### ISSUE TITLE
WZWSParser

### ISSUE THREAD

**Issue by 164072109** [songguoxiong/wenshu_utils#3]
能请问下这个解析网站卫士是怎么推导出来导吗

**Comment by songguoxiong** [comment]
这个我其实没太多技巧，也不知道怎么表达好，而且这是有些敏感的东西。

如果只是跑js的话，相对简单很多，我们可以不用关心他的加密流程，只需把js拿下来能在本地运行就ok了。
简单来说就是把它返回的"请开启JavaScript并刷新该页"的html保存到本地慢慢调，如果踩坑了可以去浏览器那边对比一下执行过程，看看哪一步和浏览器中的结果不一致，然后排错。

如果想要用其他语言实现加密，那就得反复调试很久，弄清楚加密逻辑才行。
这是一个非常枯燥的过程。

**Comment by 164072109** [comment]
谢谢解答！
